- hosts: all
  tags: always
  become: True
  pre_tasks:
    - name: pre-run | apt update
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Linux Mint", "Ubuntu", "Debian", "Pop!_OS"]
- hosts: all
  tags: base
  become: True
  roles:
    - base
- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation    