# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/fredrik.yml
  ## desktop environment
  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true  
  ## system setup
  - import_tasks: system_setup/autofs.yml
  ## install software
  - import_tasks: software/firefox.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/gnucash.yml