# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/fredrik.yml
  ## desktop environment
  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true
  - include_tasks: desktop_environments/gnome/keybindings.yml  
    when: gnome is defined and gnome == true
  - include_tasks: desktop_environments/gnome/pop_os.yaml
    when: ansible_distribution == "Pop!_OS"
  ## system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/flatpak.yml
  ## install software
  - import_tasks: software/code.yml
  - import_tasks: software/discord.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/gnucash.yml
  - import_tasks: software/joplin.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/mailspring.yml
  - import_tasks: software/virtualbox.yml
  - import_tasks: software/yakuake.yml
  - import_tasks: software/yubico.yml