- name: system setup | flatpak | install package
  tags: flatpak
  package:
    name: flatpak
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Linux Mint"]


- name: system setup | flatpak | add repo
  become_user: fredrik
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Linux Mint"]