- name: software | bottles | install package
  tags: packages,flatpak,bottles,workstation-packages
  become_user: fredrik
  flatpak:
    name:  com.usebottles.bottles
    method: user
    state: present
  when: bottles is defined and bottles == true