- name: software | visualstudio | install package
  tags: packages,flatpak,visualstudio,workstation-packages
  become_user: fredrik
  package:
    name: "{{ visualstudio_package }}" 
  when: visualstudio is defined and visualstudio == true