- name: software | visualstudio | install package
  tags: packages,flatpak,visualstudio,workstation-packages
  become_user: fredrik
  flatpak:
    name: org.visualstudio.code
    method: user
    state: present
  when: visualstudio is defined and visualstudio == true