- name: software | discord | install package
  tags: packages,flatpak,discord,workstation-packages
  become_user: fredrik
  flatpak:
    name: com.discord.Discord
    method: user
    state: present
  when: discord is defined and discord == true