- name: software | gnucash | install package
  tags: packages,flatpak,gnucash,workstation-packages
  become_user: fredrik
  flatpak:
    name: org.gnucash.GnuCash
    method: user
    state: present
  when: gnucash is defined and gnucash == true
  
- name: users | fredrik | copy personal config files
  tags: dotfiles,dotfiles-fredrik
  copy:
    src: users/fredrik/.var/app/org.gnucash.GnuCash/{{ item.src }}
    owner: fredrik
    group: fredrik
    mode: 0600
  with_items:
    - { src: 'gnucash.keyfile', dest: 'config/glib-2.0/settings/keyfile' }
    - { src: 'gnucash.reports', dest: 'data/gnucash/saved-reports-2.8'}
