- name: software | gnucash | install package
  tags: packages,flatpak,gnucash,workstation-packages
  become_user: fredrik
  flatpak:
    name: org.gnucash.GnuCash
    method: user
    state: present
  when: gnucash is defined and gnucash == true

- name: users | fredrik | create gnucash config directories
  tags: dotfiles,dotfiles-fredrik
  file:
    path: /home/fredrik/{{ item.dir }}
    state: directory
    owner: fredrik
    group: fredrik
    mode: 0700
  with_items:
    - { dir: .var }
    - { dir: .var/app }
    - { dir: .var/app/org.gnucash.GnuCash }
    - { dir: .var/app/org.gnucash.GnuCash/config }
    - { dir: .var/app/org.gnucash.GnuCash/config/glib-2.0 }
    - { dir: .var/app/org.gnucash.GnuCash/config/glib-2.0/settings }
    - { dir: .var/app/org.gnucash.GnuCash/data }
    - { dir: .var/app/org.gnucash.GnuCash/data/gnucash }
  when: gnucash is defined and gnucash == true
  
- name: users | fredrik | copy gnucash config files
  tags: dotfiles,dotfiles-fredrik
  copy:
    src: users/fredrik/{{ item.src }}
    dest: /home/fredrik/.var/app/org.gnucash.GnuCash/{{ item.dest }}
    owner: fredrik
    group: fredrik
    mode: 0600
  with_items:
    - { src: 'gnucash.keyfile', dest: 'config/glib-2.0/settings/keyfile' }
    - { src: 'gnucash.reports', dest: 'data/gnucash/saved-reports-2.8'}
  when: gnucash is defined and gnucash == true
