- name: software | joplin | install package
  tags: packages,flatpak,joplin,workstation-packages
  become_user: fredrik
  flatpak:
    name: net.cozic.joplin_desktop
    method: user
    state: present
  when: joplin is defined and joplin == true