
- name: software | steam | install package
  tags: steam,steam
  package:
    state: latest
    name: "{{ steam_package }}"
  when:
    - steam is defined
    - steam == true

- name: software | steam | install steam-devices package (debian, ubuntu, etc)
  tags: steam,steam
  package:
    state: latest
    name: steam-devices
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - steam is defined
    - steam == true

- name: install vulkan drivers (debian, ubuntu, etc)
  tags: drivers,steam
  package:
    state: latest
    name: mesa-vulkan-drivers
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - steam is defined
    - steam == true