- name: software | thunderbird | install package
  tags: packages,flatpak,thunderbird,workstation-packages
  become_user: fredrik
  flatpak:
    name: flathub org.mozilla.Thunderbird
    method: user
    state: present
  when: thunderbird is defined and thunderbird == true