- name: software | virtualbox | install package
  tags: virtualbox,packages,workstation-packages
  package:
    name: "{{ virtualbox_package }}"
  when:
    - virtualbox is defined
    - virtualbox == true
      
- name: users | fredrik | create user
  tags: fredrik,users,virtualbox
  user:
    name: fredrik
    group: fredrik
    groups: vboxusers 
    state: present
    append: yes
  when:
    - virtualbox is defined
    - virtualbox == true