- name: software | virtualbox | install package
  tags: virtualbox,packages,workstation-packages
  package:
    name: "{{ virtualbox_package }}"
  when:
    - virtualbox is defined
    - virtualbox == true