- name: software | yubico | install package
  tags: packages,flatpak,yubico,workstation-packages
  become_user: fredrik
  flatpak:
    name: com.yubico.yubioath
    method: user
    state: present
  when: yubico is defined and yubico == true

- name: software | yubico install dependencies
  tags: packages,yubico,workstation-packages
  package:
    name: pcscd
  when: yubico is defined and yubico == true

- name: software | yubico enable socket
  tags: packages,yubico,workstation-pacckages
  systemd:
    name: pcscd.socket
    state: started
    enabled: yes