- name: gnome | keybindings | disable default browser key binding
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/www", value: "@as []" }

# - name: gnome | keybindings | disable default file manager binding
  # tags: gnome,keybindings
  # become_user: fredrik
  # dconf:
    # key: "{{ item.key }}"
    # value: "{{ item.value }}"
  # with_items:
    # - { key: "/org/gnome/settings-daemon/plugins/media-keys/home", value: "@as []" }

# - name: gnome | keybindings | disable default email client binding
  # tags: gnome,keybindings
  # become_user: fredrik
  # dconf:
    # key: "{{ item.key }}"
    # value: "{{ item.value }}"
  # with_items:
    # - { key: "/org/gnome/settings-daemon/plugins/media-keys/email", value: "@as []" }

# - name: gnome | keybindings | disable default terminal key binding
  # tags: gnome,keybindings
  # become_user: fredrik
  # dconf:
    # key: "{{ item.key }}"
    # value: "{{ item.value }}"
  # with_items:
    # - { key: "/org/gnome/settings-daemon/plugins/media-keys/terminal", value: "@as []" }

- name: gnome | keybindings | set custom-keybindings
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

- name: gnome | keybindings | set primary browser keybinding
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'browser'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>w'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'{{ web_browser }}'" }
  when: web_browser is defined

- name: gnome | keybindings | set primary browser keybinding
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'browser'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>w'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'firefox'" }
  when: web_browser is not defined

- name: gnome | keybindings | open vscode 
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'code'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Super>c'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'code'" }

- name: gnome | keybindings | open joplin 
  tags: gnome,keybindings
  become_user: fredrik
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name", value: "'code'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding", value: "'<Super>j'" }
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command", value: "'flatpak run net.cozic.joplin_desktop'" }
# - name: gnome | keybindings | set browser (alternate) keybinding
#   tags: gnome,keybindings
#   become_user: fredrik
#   dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value}}"
#   with_items:
#     - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name", value: "'browser-alt'" }
#     - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding", value: "'<Shift><Super>b'" }
#     - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command", value: "'/usr/bin/google-chrome'" }








# Uncommenting the below plays will restore the default GNOME shortcuts for these actions:
#- name: gnome | keybindings | set keybindings for switching between workspaces
#  become_user: fredrik
#  dconf:
#    key: "{{ item.key }}"
#    value: "{{ item.value}}"
#  with_items:
#      - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down", value: "['<Super>Page_Down']" }
#      - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-up", value: "['<Super>Page_Up']" }

#- name: gnome | keybindings | set key binding for moving windows to other workspaces
#  become_user: fredrik
#  dconf:
#    key: "{{ item.key }}"
#    value: "{{ item.value}}"
#  with_items:
#      - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down", value: "['<Shift><Super>Page_Down']" }
#      - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up", value: "['<Shift><Super>Page_Up']" }

#- name: gnome | keybindings | set maximize/minimize key bindings
#  become_user: fredrik
#  dconf:
#    key: "/org/gnome/desktop/wm/keybindings/{{ item.key }}"
#    value: "{{ item.value}}"
#  with_items:
#      - { key: maximize, value: "'<Super>Up'" }
#      - { key: unmaximize, value: "'<Super>Down'" }
