- name: system setup | development packages | install packages
  tags: dev,development,packages,python,ruby
  package:
    name:
      - git
      - perl
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - "{{ python_setuptools_package }}"
      - "{{ python_virtualenv_package }}"
      - docker.io
    state: latest

- name: system setup | add user to docker group
  tags: dev,development,group
  user:
    name: fredrik
    groups: docker
    append: yes