- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - curl
      - htop
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - rsync
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh

- name: system setup | utilities | install utility not for rocky
  tags: packages,system,settings
  package:
    state: latest
    name:
      - ripgrep
  when: ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]