- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - curl
      - htop
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - rsync
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh