- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
- block:
#setup users
  - import_tasks: users/fredrik.yml
#setup ansible environment
  - import_tasks: ansible_setup.yml
#install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml

    # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
#  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/openssh.yml

  rescue:
    - set_fact: task_failed=true